version: '2'

services:

  postgres:
    container_name: teamladders_postgres
    image: postgres:9.6.1
    volumes:
      - "${TEAMLADDERS_STORAGE_ROOT}/postgres:/var/lib/postgresql/data"
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    container_name: teamladders_redis
    image: redis:3.0.7
    volumes:
      - "${TEAMLADDERS_STORAGE_ROOT}/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    ports:
        - 127.0.0.1:6379:6379

  nginx:
    container_name: teamladders_nginx
    image: nginx:1.11.8
    volumes:
      - "${TEAMLADDERS_STORAGE_ROOT}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${TEAMLADDERS_STORAGE_ROOT}/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "${TEAMLADDERS_STORAGE_ROOT}/nginx/log:/var/log/nginx"
      - "${TEAMLADDERS_STORAGE_ROOT}/work:/work"
    restart: always
    ports:
      - 127.0.0.1:3000:80
    depends_on:
      - fpm

  fpm:
    container_name: teamladders_fpm
    build: .
    restart: always
    volumes:
      - "${TEAMLADDERS_STORAGE_ROOT}/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "${TEAMLADDERS_STORAGE_ROOT}/work:/work"
    depends_on:
      - postgres
      - redis
